server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.0.1.196:3100/loki/api/v1/push

scrape_configs:
  - job_name: kokomen-app-prod
    static_configs:
      - labels:
          job: kokomen-app
          app: kokomen
          host: ${HOSTNAME}
          __path__: /logs/app/app.log
    pipeline_stages:
      - multiline:
          firstline: '^\[[^\]]+\]\s\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\.\d{3}\s[^\[]+\s\[[^\]]+\]'
      - regex:
          expression: '\[.*?\] [\d\-:.\s]+ [^\[\]]+ \[.*?\]\s+(?P<level>[A-Z]+)\s+[^\s]+'
      - labels:
          level:
